name: Build Terraform Toolkit Image

on:
  push:
    branches:
      - main
      - feature/multi-arch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub or another container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-base-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-base-buildx-

      # Build the Docker image
      - name: Build and Push Docker image
        run: |
          GIT_SHORT_SHA=${GITHUB_SHA::7}
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:${GIT_SHORT_SHA} \
            -t ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:latest \
            -f Dockerfile . \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache
