name: Build Terraform Toolkit Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub or another container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:latest .

      # Tag the image with a 7-digit tag based on the GitHub SHA or GitHub Run Number
      - name: Push Docker Image
        run: |
          # Generate a 7-digit tag based on the first 7 characters of the GitHub SHA
          IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-7)
          docker tag ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:latest ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/terraform-toolkit:${IMAGE_TAG}
